flowstanddb/urls.py
"""flowstanddb URL Configuration"""

from .settings import MEDIA_ROOT, DEBUG, MEDIA_URL
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView, TemplateView
from django.contrib.auth.decorators import login_required
from flowstanddb.views import editProfileView, user_list


urlpatterns = [

    url(r'^$', 'flowstands.views.flowstands_list', name='home'),

    url(r'^flowstand/(?P<pk>\d+)/$', 'flowstands.views.flowstand_view', name='flowstand_view'),

    url(r'^documents/$', 'flowstands.views.documents', name='documents'),

    url(r'^customers/$', 'flowstands.views.customers_list', name='customers'),

    url(r'^manufactors/$', 'flowstands.views.manufactors_list', name='manufactors'),

    url(r'^national_standards/$', 'flowstands.views.national_standards', name='national_standards'),

    url(r'^national_standards/(?P<pk>\d+)/$', 'flowstands.views.national_standard', name='national_standard'),

    url(r'^contact/$', 'flowstands.views.contact_admin', name='contact'),

# User Related urs:
    url(r'^user_list/$', user_list, name='user_list'),
    url(r'^users/profile/(?P<pk>\d+)/edit/$', login_required(editProfileView.as_view()), name='profile_edit'),
    url(r'^users/profile/$', login_required(TemplateView.as_view(template_name='registration/profile.html')),
      name='profile'),
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page':'home'},
          name='auth_logout'),
    url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),
          name='registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls', namespace='users')),

    url(r'^admin/', include(admin.site.urls)),

]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

flowstands/models.py
# -*- coding: utf-8 -*-

from django.db import models


# Region Model

class Region(models.Model):
    class Meta(object):
        verbose_name = u"Область"
        verbose_name_plural = u"Області"

    name = models.CharField(
        max_length=50,
        blank=False,
        verbose_name=u"Область")

    def __unicode__(self):
        return u"%s" % self.name


# Flow standard Model

class Flowstand(models.Model):
    class Meta(object):
        ordering = ['region', 'date_calibr']
        verbose_name = u"Робочий еталон"
        verbose_name_plural = u"Робочі еталони"
        app_label = 'flowstands'

    region = models.ForeignKey('Region',
                               blank=False,
                               null=True,
                               verbose_name=u"Область",
                               on_delete=models.SET_NULL)

    customer = models.ForeignKey('Customer',
                                 blank=False,
                                 null=True,
                                 verbose_name=u"Власник",
                                 on_delete=models.SET_NULL)

    name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Назва")

    flow_range = models.CharField(
        max_length=30,
        blank=False,
        verbose_name=u"Діапазон")

    serial_number = models.CharField(
        max_length=20,
        blank=False,
        verbose_name=u"Зав.номер")

    manufactor = models.ForeignKey('Manufactor',
                                   blank=True,
                                   null=True,
                                   verbose_name=u"Виробник",
                                   on_delete=models.PROTECT)

    certificate = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        unique=True,
        verbose_name=u"Сертифікат")

    date_calibr = models.DateField(
        blank=True,
        null=True,
        verbose_name=u"Дата калібрування")

    traceability = models.CharField(
        max_length=256,
        blank=True,
        null=True,
        verbose_name=u"Простежуваність")

    placeholder = models.CharField(
        max_length=80,
        blank=True,
        null=True,
        verbose_name=u"Адреса розміщення")

    def __unicode__(self):
        return u"%s, № %s %s" % (self.name, self.serial_number, self.customer)


# Manufactor Model

class Manufactor(models.Model):
    class Meta(object):
        verbose_name = u"Виробник"
        verbose_name_plural = u"Виробники"

    name = models.CharField(
        max_length=50,
        blank=False,
        verbose_name=u"Назва")

    agent = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name=u"Контактна особа")

    address = models.CharField(
        max_length=256,
        blank=True,
        null=True,
        verbose_name=u"Адреса")

    contacts = models.CharField(
        max_length=256,
        blank=True,
        null=True,
        verbose_name=u"Контактні дані")

    email = models.EmailField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name=u"Електронна пошта")

    def __unicode__(self):
        return u"%s" % self.name


# Customer Model

class Customer(models.Model):
    class Meta(object):
        ordering = ['region']
        verbose_name = u"Власник"
        verbose_name_plural = u"Власники"

    region = models.ForeignKey('Region',
                               blank=False,
                               null=True,
                               verbose_name=u"Область",
                               on_delete=models.SET_NULL)

    name = models.CharField(
        max_length=200,
        blank=False,
        verbose_name=u"Назва")

    agent = models.CharField(
        max_length=100,
        blank=False,
        null=True,
        verbose_name=u"Контактна особа")

    address = models.CharField(
        max_length=256,
        blank=True,
        null=True,
        verbose_name=u"Адреса")

    contacts = models.CharField(
        max_length=256,
        blank=True,
        null=True,
        verbose_name=u"Контактні дані")

    email = models.EmailField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name=u"Електронна пошта")

    def __unicode__(self):
        return u"%s" % self.name


# National Standard Model

class NationalStandard(models.Model):

    name = models.CharField(
        max_length=120,
        blank=True,
        null=True,
        verbose_name=u"Назва еталона"
    )
    short_name = models.CharField(
        max_length=30,
        blank=False,
        verbose_name=u"Позначення"
    )
    flow_range = models.CharField(
        max_length=30,
        blank=False,
        verbose_name=u"Діапазон витрат"
    )
    image = models.FileField(
        upload_to="images/",
        blank=True,
        verbose_name=u'Фото'
    )
    description = models.TextField(
        max_length=1000,
        blank=True,
        verbose_name=u"Опис еталона"
    )
    keeper = models.CharField(
        max_length=40,
        blank=True,
        verbose_name=u"Вчений зберігач"
    )
    artefacts = models.CharField(
        max_length=256,
        blank=True,
        verbose_name=u'Типи досліджуваних приладів'
    )
    diameters = models.CharField(
        max_length=200,
        blank=True,
        verbose_name=u'Діаметри умовних проходів'
    )

    def __unicode__(self):
        return u"%s" % self.short_name

    class Meta(object):
        verbose_name = u"Національний еталон"
        verbose_name_plural = u"Національні еталони"


class Documents(models.Model):
    title = models.CharField(
        max_length=300,
        verbose_name=u'назва'
    )
    edition = models.IntegerField(
        verbose_name=u'редакція'
    )
    file = models.FileField(
        upload_to='documents/',
        verbose_name=u'файл'
    )

    class Meta(object):
        verbose_name = u'Нормативний документ'
        verbose_name_plural = u'Нормативні документи'

flowstands/forms.py
# -*- coding: utf-8 -*-

from django import forms


default_text = u'Назва еталона або власника'

class SearchForm(forms.Form):
    q = forms.CharField(
        max_length=20,
        widget=forms.TextInput(attrs={
            'id': 'search',
            'class': 'form-control',
            'placeholder': default_text
        })
    )

flowstands/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from .models import Flowstand, Manufactor, Customer, NationalStandard, Documents
from datetime import date, timedelta
from django.core.urlresolvers import reverse
from django.contrib import messages

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit

from .util import paginate, get_current_region
from .util import search

import sendgrid
from sendgrid.helpers.mail import *
from flowstanddb.settings import ADMIN_EMAIL, SENDGRID_API_KEY


##########################################################################

# Flow standards Views

def flowstands_list(request):
    flowstands = Flowstand.objects.all().filter(traceability__icontains="Івано-Франківськ")
    # кількість еталонів у базі
    count = flowstands.count()
    # визначення поточного регіону
    current_region = get_current_region(request)
    if current_region:
        flowstands = flowstands.filter(region=current_region)

    sort_param = 'date_calibr'
    order_by = request.GET.get('order_by', '')
    if order_by:
        if request.GET.get('reverse', '') == '1':
            sort_param = ''.join(('-', sort_param))
        flowstands = flowstands.order_by(sort_param)

    search_count = None
    result_text = ''
    result_text_dict = {('1',): 'еталон',
                        ('2', '3', '4'): 'еталони',
                        ('0', '5', '6', '7', '8', '9'): 'еталонів'}
    search_terms = ('name', 'customer__name')
    q = request.GET.get('q', '')
    if q:
        if len(q) >= 3:
            flowstands = search(q, flowstands, search_terms, sort_param)
            search_count = len(flowstands)
            if len(str(search_count)) == 2 and str(search_count).startswith('1'):
                result_text = 'еталонів'
            else:
                for i in result_text_dict.keys():
                    if str(search_count)[-1] in i:
                        result_text = result_text_dict[i]
        else:
            flowstands = []

    today = date.today()
    context = paginate(flowstands, 15, request, {}, var_name='flowstands')
    context['q'] = q
    context['count'] = count
    context['today'] = today
    context['search_count'] = search_count
    context['result_text'] = result_text

    return render(request, 'flowstands/flowstands_list.html', context)


########################################################################
# Flowstand Detail Views

def flowstand_view(request, pk):
    flowstand = Flowstand.objects.get(id=pk)
    today = date.today()
    # calculation of certificate expiration date
    delta = timedelta(days=365)
    expir_date = flowstand.date_calibr + delta
    diff = (today - flowstand.date_calibr).days
    diff = 365 - int(diff)

    return render(request, 'flowstands/flowstand_view.html', {
        'flowstand': flowstand,
        'today': today,
        'expir_date': expir_date,
        'diff': diff
    }
                  )


##########################################################################
# Customers Views

def customers_list(request):
    current_region = get_current_region(request)
    if current_region:
        customers = Customer.objects.filter(region=current_region)
    else:
        customers = Customer.objects.all()
    context = paginate(customers, 10, request, {}, var_name='customers')

    return render(request, 'flowstands/customers_list.html', context)


#############################################################
# Manufactors Views

def manufactors_list(request):
    manufactors = Manufactor.objects.all()
    context = paginate(manufactors, 15, request, {}, var_name='manufactors')
    return render(request, 'flowstands/manufactors_list.html', context)


# National Standards list #################################################
def national_standards(request):
    nat_standards = NationalStandard.objects.all()
    return render(request, 'flowstands/nat_standards.html', {'nat_standards': nat_standards})


# View of selected National Standard
def national_standard(request, pk):
    nat_standard = NationalStandard.objects.get(id=pk)
    return render(request, 'flowstands/nat_standard.html', {'nat_standard': nat_standard})


# Contact Admin ###################
class ContactForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()

        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('contact')

        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-4 control-label'
        self.helper.field_class = 'col-sm-8'
        self.helper.layout = Layout(
            'from_email',
            'subject',
            'message',
            Div(
                Div(
                    Submit('send_button', u'Надіслати'),
                    css_class='col-sm-offset-4 col-sm-12'
                ),
                css_class='form-group'
            )
        )

    from_email = forms.EmailField(
        label=u'Ваш Е-мейл')
    subject = forms.CharField(
        label=u'Заголовок',
        max_length=128)
    message = forms.CharField(
        label=u'Текст повідомлення',
        max_length=2560,
        widget=forms.Textarea)


def contact_admin(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            sg = sendgrid.SendGridAPIClient(apikey=SENDGRID_API_KEY)
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            content = Content("text/plain", message)
            from_email = Email(form.cleaned_data['from_email'])
            to_email = Email(ADMIN_EMAIL)

            try:
                mail = Mail(from_email, subject, to_email, content)
                response = sg.client.mail.send.post(request_body=mail.get())
            except Exception:
                message = u'Під час відправки листа виникла помилка'
                messages.warning(request, message)
            else:
                message = u'Повідомлення успішно надіслане!'
                messages.success(request, message)
                return HttpResponseRedirect(reverse('contact'))
    else:
        form = ContactForm()
    return render(request, 'contact_admin/form.html', {'form': form})

# Normative documents
def documents(request):
    documents = Documents.objects.all()
    return render(request, 'flowstands/documents.html', {'documents': documents})

flowstands/templates/flowstands/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="uk">
	<head>
		<meta charset='UTF-8'/>
		<title>Еталони витрати газу України - {% block meta_title %}{% endblock meta_title %}</title>
		<meta name="description" value="Еталони витрати газу України" content="База даних робочих еталонів об'єму та об'ємної
		витрати газу України, та інформація про їх власників, виробників та калібрування"/>
		<meta name="keywords" content="еталон об'єму газу, калібрування, база даних еталонів, витрата газу"/>
		<meta name="viewport" content="width=device-width, initial-sale=1"/>

		<!-- Include Styles -->

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
		integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		<link rel="stylesheet" href="{{ PORTAL_URL }}{% static "css/main.css" %}">

		{% block extra_css %}{% endblock extra_css %}

	</head>

	<body>
	    <!-- Google Tag Manager (noscript) -->
            <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MRPRDTF"
            height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->

		<!-- Start Container -->
		<div class="container wrap">
				<!-- Start Logo -->
				<div class="col-xs-8">
					<h1>Еталони витрати газу України</h1>
				</div>

				<!-- Region Selector -->
				{% block selector %}
					<div class="col-xs-4" id="region-selector">
						<strong>Область: </strong>
						<select>
							<option value="">Усі області</option>
							{% for region in REGIONS %}
							<option value="{{ region.id }}"{% if region.selected %} selected="1"{% endif %}>
								{{region.name}}</option>
							{% endfor %}
						</select>
					</div>
				{% endblock selector %}

				<!-- Navigation -->
					<div class="col-xs-12">
						<ul class="nav nav-tabs" role="tablist">
							<li role="presentation" {% if request.path == '/' %}class="active"{% endif %}>
								<a href="{% url "home" %}">Робочі еталони</a>
							</li>
                            <li role="presentation" {% if '/national_standards' in request.path %}class="active"{% endif %}>
								<a href="{% url "national_standards" %}">Національні еталони</a>
							</li>
							<li role="presentation" {% if '/manufactors' in request.path %}class="active"{% endif %}>
								<a href="{% url "manufactors" %}">Виробники</a>
							</li>
							<li role="presentation" {% if '/customers' in request.path %}class="active" {% endif %}>
								<a href="{% url "customers" %}">Власники</a>
							</li>
                            <li role="presentation" {% if 'contact' in request.path %}class="active" {% endif %}>
								<a href="{% url "contact" %}">Контакти</a>
							</li>
							{% if perms.flowstands.add_flowstand %}
                                <li role="presentation" {% if '/admin' in request.path %}class="active" {% endif %}>
                                    <a href="/admin">Адміністрування</a>
                                </li>
                            {% endif %}
							<li role="presentation" {% if '/user_list' in request.path %}class="active" {% endif %}>
								<a href="{% url "user_list" %}">Користувачі</a>
							</li>
							{% if user.is_authenticated %}
							<li role="presentation" {% if '/profile' in request.path %}class="active" {% endif %}>
								<a href="{% url "profile_edit" user.id %}">Мій профіль</a>
							</li>
							{% endif %}
                            <li role="presentation" {% if '/documents' in request.path %}class="active"{% endif %}>
								<a href="{% url "documents" %}">Нормативні документи</a>
							</li>
						</ul>
					</div>
                    {% block breadcrumb %}{% endblock breadcrumb %}
				<div class="col-xs-8 title">
					<h2>{% block title %}{% endblock title %}</h2>
				</div>
                {% if user.is_authenticated %}
                <!-- User's toolbar for authenticated users -->
                    <div class="col-xs-4" id="user-toolbar">
                        <a href="{% url "profile" %}">{{ user.get_full_name|default:user.username }}</a> |
                        <a href="{% url "users:auth_logout" %}">Вийти</a>
                    </div>
                {% else %}
                <!-- User's toolbar for anonymous users -->
                    <div class="col-xs-4" id="user-toolbar">
                        <a href="{% url "users:auth_login" %}">Увійти</a> |
                        <a href="{% url "users:registration_register" %}">Реєстрація</a>
                    </div>
                {% endif %}

				{% block search %}{% endblock search %}

				<!-- Start Content Columns -->
				<div class="col-xs-12 content">
				    {% block status_message %}
				    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{% if message.tags == 'warning' %}warning{% elif message.tags == 'success' %}success{% else %}danger{% endif %}" role="alert">{{ message }}</div>
                        {% endfor %}
                	{% endif %}
                	{% endblock status_message %}
					{% block content %}{% endblock content %}
				</div>
				<!-- End Content Columns -->


				<!-- Footer -->
				<div class="container footer">
						{% block pagination %}{% endblock pagination %}
					<div class="col-xs-12 copyright">
						&copy; 2017 <a href="http://www.ifdcsms.com.ua">ДП "Івано-Франківськстандартметрологія"</a>
					</div>
					<div id="scrollup" style="display: none; opacity: 0.8;">
						<img class="up" alt="to top" src="/static/images/scrollUp.png">
					</div>
				</div>
				<!-- End Footer -->
		<!-- End Container -->
		</div>


		<!-- Modal Boilerplate -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
			aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span></button>
						<h3 class="modal-title" id="myModalLabel"><!-- --></h3>
					</div>
					<div class="modal-body"><!-- --></div>
					<div class="modal-footer">
					    <button type="button" class="btn btn-default" data-dismiss="modal">Закрити</button>
					</div>
				</div>
			</div>
		</div>


		<!-- Javascripts Section -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
		<script src ="{{ PORTAL_URL }}{% static "js/jquery.cookie.js" %}"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
		integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
		crossorigin="anonymous"></script>
        <script src="{{ PORTAL_URL }}{% static "js/main.js" %}"></script>
		<script type="text/javascript">
		    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    		})
	    	(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
		        ga('create', 'UA-88279337-1', 'auto');
		        ga('send', 'pageview');
		</script>
		{% block extra_js %}{% endblock extra_js %}

	</body>

</html>

flowstands/templates/flowstands/customers_list.html
{% extends "flowstands/base.html" %}

{% load static from staticfiles %}

{% block meta_title %}Еталони витрати газу{% endblock meta_title %}

{% block title %}Власники{% endblock title %}

{% block content %}
			
<!-- Start Customers Listing -->
<table class="table table-hover table-striped table-condensed">
	<thead>
		<tr>
			<th width="5%">№</th>
			<th width="15%">Область</th>
			<th width="25%">Назва</th>
			<th width="35%">Адреса</th>
			

	</thead>
						
						
<!--Тіло таблиці списку споживачів-->						
	<tbody>
		{% for customer in customers %} <!-- Наповнення таблиці циклом -->
		<tr>
			<td>{{ forloop.counter0|add:customers.start_index }}</td>
			<td>{{ customer.region }}</td>
			<td> {{ customer.name }}</td>
			<td>{{ customer.address }}</td>
			
		</tr>
		{% endfor %}
	
	</tbody>
					
</table>
						
					<!-- End Content Columns -->

					
<!-- Pagination -->
					{% with object_list=customers %}
						{% include "flowstands/pagination.html" %}
					{% endwith %}


{% endblock content %}				

flowstands/templates/flowstands/documents.html
{% extends "flowstands/base.html" %}

{% load static %}

{% block title %}
	 Нормативні документи
{% endblock title %}

{% block content %}
<div class="container">

	<ul class="document_list">
			{% for document in documents %}
				<li>
					<a href="{% if document.file %}{{ document.file.url }}{% else %}#{% endif %}">{{ document.title }}</a>
				</li>
			{% endfor %}
	</ul>



</div>
{% endblock content %}

flowstands/templates/flowstands/flowstand_view.html
{% extends "flowstands/base.html" %}

{% block meta_title %}Еталони витрати газу{% endblock meta_title %}

{% block title %}Робочий еталон: {{flowstand.name}},  №{{flowstand.serial_number}}{% endblock title %}

{%block selector%}{%endblock selector%}

{% block content %}
	
<!-- Start Customers Listing -->
<table class="table table-hover table-striped">
	<colgroup>
		<col class="col-xs-2">
		<col class="col-xs-4">
	<tbody>
		<tr>
			<th>Діапазон витрат</th>
			<td>{{ flowstand.flow_range }}</td>
		</tr>
		
		<tr>
			<th>Власник</th>
			<td>{{ flowstand.customer }}</td>
		</tr>
		
		<tr>
			<th>Виробник</th>
			<td>{{ flowstand.manufactor }}</td>
		</tr>
		
		<tr>
			<th>Адреса розташування</th>
			<td>{{ flowstand.placeholder }}</td>
		</tr>
		
		<tr>
			<th>Дата калібрування</th>
			<td>{{ flowstand.date_calibr }}</td>
		</tr>
		
		<tr>
			<th>Сертифікат</th>

			<td>{% if today > expir_date %}
					<font color="red">Термін дії сертифікату вийшов</font>
				{% else %}
					{{ flowstand.certificate }}</br>
					до закінчення дії сертифіката залишилось <strong>{{diff}}</strong> дн.
				{% endif %}
			</td>
		</tr>
		<tr>
			<th>Простежуваність</th>
			<td>{{ flowstand.traceability }}</td>
		</tr>
		
	</tbody>
					
</table>

<!-- End Content Columns -->
{% endblock content %}				

	

flowstands/templates/flowstands/flowstands_list.html
{% extends "flowstands/base.html" %}

{% load static from staticfiles %}

{% load search_tags %}

{% block meta_title %}База еталонів{% endblock meta_title %}

{% block title %}Робочі еталони{% endblock title %}

{% block search %}
    <div class="col-xs-12 col-sm-12 col-md-12">
        {% search_box request %}
    </div>
    {% if q %}
        <div class="col-xs-12 col-sm-12 col-md-12">
            <p style="margin: 10px 0 0 20px;">За Вашим запитом знайдено <span class="db_info">{{ search_count }}</span> {{ result_text }}</p>
        </div>
    {% endif %}
{% endblock search %}

{% block breadcrumb %}
    {% if q %}
        <div class="col-xs-12 col-md-12 col-lg-12">
        <ol  class="breadcrumb">
            <li><a href="{% url 'home' %}">Робочі еталони</a></li>
            <li class='active'>Результати пошуку</li>
        </ol>
        </div>
    {% endif %}
{% endblock breadcrumb %}

	{% block content %}

			<!-- Start Flow Standards Listing -->
			<table class="table table-hover table-striped table-condensed">
            {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
				<thead>
					<tr>
						<th width="3%">№</th>
						<th width="18%">Область</th>
						<th width="24%">Власник</th>
						<th width="10%">Назва</th>
						<th width="10%">Діапазон</th>
						<th width="10%">Зав. номер</th>
						<th width="20%">
                            <a href="{% url "home" %}?order_by=date_calibr{% if order_by == 'date_calibr' and reverse != '1' %}&amp;reverse=1{% endif %}{% if q %}&amp;q={{ q }}{% endif %}">
                                    Дата калібрування
								    {% if order_by == 'date_calibr' and reverse != '1' %}
                                        <img src="{% static "images/arrow_up.png" %}" height="20" width="20"/>
								    {% elif order_by == 'date_calibr' and reverse == '1' %}
									    <img src="{% static "images/arrow_down.png" %}" height="20" width="20"/>
                                    {% endif %}
                            </a>
                        </th>
					</tr>
                {% endwith %}
				</thead>
										
				<!--Тіло таблиці списку еталонів-->						
				<tbody>
				{% for flowstand in flowstands %} <!-- Наповнення таблиці циклом -->
					<tr>
					
						<td>
						
							{{ forloop.counter0|add:flowstands.start_index }}
										
						</td>
						<td>{{ flowstand.region }}</td>
						<td>{{ flowstand.customer }} </td>
						<td><a href="{% url "flowstand_view" flowstand.id %}"class="flowstand_show-link">
							{{ flowstand.name }}</td>
						<td>{{ flowstand.flow_range }}</td>
						<td>{{ flowstand.serial_number }}</td>
						<td>{{ flowstand.date_calibr }}</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>

	<!-- End Content Columns -->	

	<!-- Pagination -->
<div id="pager_and_count ">
    {% with object_list=flowstands %}
        {% include "flowstands/pagination.html" %}
    {% endwith %}
<p><b>Загальна кількість еталонів у базі:  <span class="db_info">{{ count}}<span></b></p>
<p><b>станом на <span class="db_info">{{ today }}</span></b></p>

</div>
	<!-- End of Pagination-->
	{% endblock content %}

	

flowstands/templates/flowstands/search.html
<form class="form-inline"
					action="{% url "home" %}" method="get">
					<input type="text" class="form-control" id="search" placeholder="Назва еталона або власник" name="q">
					<input type="submit" class="btn btn-primary" value="Пошук">
			</form>